### ISSUE TITLE
hash based sharding is not supporting

### ISSUE THREAD

**Issue by samperman** [edelight/chef-mongodb#227] opened 2014-01-31 16:57 UTC
Inside `libaries/mongodb.rb`:

```
def self.configure_sharded_collections(node, sharded_collections)

    ... snipped ...

    sharded_collections.each do |name, key|
      cmd = BSON::OrderedHash.new
      cmd['shardcollection'] = name
      cmd['key'] = {key => 1}
```

This code sets up the sharding for each collection, but it does not support hash based sharding.  (That "key => 1" block would need to read "key => 'hashed'")

Perhaps the sharded_collections attribute should be a map of maps?

```
{
  "mongodb": {
    "sharded_collections": {
      "test.addressbook": { "name": "hashed"} ,
      "mydatabase.calendar": { "date": 1}
    }
  }
}
```

**Comment by dave-leblanc** [comment] 2014-02-20 18:36
Just wondering if this issue is currently on anyone's radar. I've encountered this issue in working on deployments myself and if no one is working on the changes I may take a stab at getting a PR setup for this

**Comment by josephholsten** [comment] 2014-07-02 19:01
Looks like this is a duplicate of #158.

@jamesonjlee this looks safe to close.

**Comment by jamesonjlee** [comment] 2014-07-02 21:25
yep, and solving #158 would allow this and solve the underlying problem that will happen.

**Closed as completed by jamesonjlee** 2014-07-02 21:25 UTC
