### ISSUE TITLE
mongos fails to start

### ISSUE THREAD

**Issue by msaffitz** [edelight/chef-mongodb#173] opened 2013-11-22 03:39 UTC
Against HEAD, the `/etc/mongodb.conf` file is configured assuming the instance is a `mongod`, which then breaks `mongos` and `/etc/init.d/mongos` because the various parameters are not valid for it.

**Comment by msaffitz** [comment] 2013-11-22 07:57
I have a very hacky fix for this at https://github.com/apptentive-engineering/chef-mongodb/tree/mongos_fix

**Comment by krukgit** [comment] 2013-11-22 10:19
I can confirm the changes work. Thanks @msaffitz :+1: 

Btw, even after applying the changes I was receiving connection error in `ruby_block[config_sharding]` 

```
[2013-11-22T08:43:40+00:00] WARN: Could not connect to database: 'localhost:27017', reason Failed to connect to a master node at localhost:27017
[2013-11-22T08:43:40+00:00] WARN: Could not connect to database: 'localhost:27017', reason Failed to connect to a master node at localhost:27017
```

Apparently `mongos` wasn't starting fast enough. I added 2s sleep at the beginning of the block and everything works fine now.

**Comment by jamesonjlee** [comment] 2013-11-25 04:15
so I'm split about this,

The update to 0.14 was to help deploy a mongodb single instance as-is.  I believe if you are at a considering of mongos or shards/replicaset, you should be learning about the configuration, which would be reflected in changes in business logic cookbooks.  Albeit I don't see why we couldn't keep a list of config attributes not allowed on instance types in the attributes somewhere.

The issues with search (I am sure @josephholsten can chime in on this) is that, I am not a fan of how search nor am I for imposing a orchestration layer on with this cookbook.  Orchestration should be business logic unless someone comes out with a "this is how to orchestrate in your chef nodes blog post + recipe/cookbooks).  This however has the unfortunate side effect of making the replicaset/mongos/shard recipes being broken often.  The best middle ground I can conceive is a idle/looping in the node.search commands for configsrv/masters in the included recipes but it's not that pretty.

I will update the RFC for 1.0 release roadmap with the changes I intend to pin for 0.14 (PR/Issue closing), 0.15(Testing) and 0.16(HWRP-cation) soon...

**Comment by jamesonjlee** [comment] 2013-11-25 04:16
I will accept that change to the default recipe for not doing mongodb_instance for mongos recipe.

**Comment by josephholsten** [comment] 2014-01-18 04:04
@msaffitz could you put this patch in a PR? I can't figure out what you changed in that branch. I'm currently attempting to add testing for the mongos use case, so this is very relevant to my interests.

**Comment by msaffitz** [comment] 2014-01-18 23:31
@josephholsten it looks like my change is this commit: https://github.com/apptentive-engineering/chef-mongodb/commit/e299aaaf168143229bfbc7c7065069be46219613

**Comment by jspiewak** [comment] 2014-02-01 12:51
If #212 was chosen over #213, this issue can be closed now, right?

**Comment by josephholsten** [comment] 2014-07-01 21:40
@jamesonjlee looks like this can be closed

**Closed as completed** 2014-07-02 18:02 UTC
Labels: bug
