### ISSUE TITLE
How to make three mongo instances on one machine?

### ISSUE THREAD

**Issue by AlexAkulov** [edelight/chef-mongodb#278] opened 2014-04-02 13:22 UTC
What i'm trying to do is to install three mongo instances on one machine, for example: 
1. Replicaset mongo-one
2. Replicaset mongo-two
3. Arbiter for mongo-one

I would like to do this in 3-recipes and not share values via JSON.
The my recipe for mongo-one is:

```
include_recipe 'mongodb::install'
include_recipe 'mongodb::mongo_gem'

node.default[:mongodb][:is_replicaset] = true
node.default[:mongodb][:is_shard] = false
node.default[:mongodb][:auto_configure][:replicaset] = true
node.default[:mongodb][:auto_configure][:sharding] = false
node.default[:mongodb][:cluster_name] = 'ReplSetOne'

# Instanse One
unless node.mongodb.is_shard
  mongodb_instance 'mongo-one' do
    mongodb_type 'mongod'
    port         '27018'
    logpath      '/var/log/mongodb/mongo-one.log'
    dbpath       '/var/lib/mongo-one'
    replicaset   'newReplOne'
    enable_rest  true
    smallfiles   true
  end
end
```

But nothing works. What am I doing wrong?

**Comment by kikicarbonell** [comment] 2014-04-09 00:51
I have similar problem to configure multiple instances of mongo on one machine, see issue #270

**Comment by kikicarbonell** [comment] 2014-04-09 00:52
:+1:

**Comment by jamesonjlee** [comment] 2014-04-09 22:55
the recipe currently doesn't work with multiple instances of mongod on a single node.  we are trying to resourcify the recipe so that's possible again.

**Comment by josephholsten** [comment] 2014-04-10 19:39
Just wondering, why do you want to run three on the same box? Testing?

**Comment by josephholsten** [comment] 2014-07-03 03:20
Seems like a duplicate of #270 

@jamesonjlee seems like we can close this

**Closed as completed** 2014-07-06 07:12 UTC
