### ISSUE TITLE
Can't install on Ubuntu precise64 vagrant base box

### ISSUE THREAD

**Issue by argent-smith** [edelight/chef-mongodb#99] opened 2013-04-15 20:32 UTC
The complete console log is here: https://gist.github.com/argent-smith/5391009

**Comment by jamesonjlee** [comment] 2013-05-22 23:02
this looks like it was a duplicate of #100 
I will leave this one open until I verify.

**Comment by jamesonjlee** [comment] 2013-05-29 23:04
This is probably a chef problem.

**Closed as completed by jamesonjlee** 2013-05-29 23:04 UTC
