### ISSUE TITLE
mongos question

### ISSUE THREAD

**Issue by dquiles** [edelight/chef-mongodb#245] opened 2014-02-14 02:59 UTC
is it possible to have multiple mongos configs on a single node?

**Comment by jamesonjlee** [comment] 2014-02-14 03:38
currently no, in theory yes!

**Comment by dquiles** [comment] 2014-02-14 03:42
Yeah I do it now manually, wanted to use the cookbook to do it...

**Comment by jamesonjlee** [comment] 2014-02-14 16:31
yeah, it isn't a focus because it's a setup that's not recommend.  If you are talking about testing setups I have a branch I am testing with https://github.com/chrisroberts/vagabond that does multi-node environment with LXC on a single host.

**Comment by josephholsten** [comment] 2014-07-03 03:17
Seems like a duplicate of #270.

@jamesonjlee seems like we can close this.

**Closed as completed** 2014-07-06 07:27 UTC
